-- Create "certificates" table
CREATE TABLE `certificates` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `certificate_id` varchar(36) NOT NULL COMMENT 'UUID for certificate',
  `user_id` int unsigned NOT NULL COMMENT 'Foreign key to users table',
  `certificate_name` varchar(255) NOT NULL COMMENT 'Name of the certificate',
  `certificate_type` varchar(100) NULL COMMENT 'Type of certificate (e.g., TOEFL ITP PREDICTION, IELTS)',
  `certificate_number` varchar(100) NULL COMMENT 'Certificate number (e.g., 017/SAC/TOEFL/XI/2025)',
  `issued_date` date NOT NULL COMMENT 'Date when certificate was issued',
  `test_date` date NULL COMMENT 'Date when test was taken',
  `valid_until` date NULL COMMENT 'Certificate validity end date',
  `listening_score` int NULL COMMENT 'Listening score for TOEFL',
  `structure_score` int NULL COMMENT 'Structure score for TOEFL',
  `reading_score` int NULL COMMENT 'Reading score for TOEFL',
  `overall_score` int NULL COMMENT 'Overall score',
  `director_name` varchar(255) NULL DEFAULT 'Riko Susiloputro' COMMENT 'Director name on certificate',
  `certificate_url` varchar(500) NULL COMMENT 'External URL to certificate file',
  `description` text NULL COMMENT 'Additional description',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `certificate_id_UNIQUE` (`certificate_id`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_certificate_type` (`certificate_type`),
  INDEX `idx_issued_date` (`issued_date`),
  INDEX `idx_created_at` (`created_at`),
  CONSTRAINT `fk_certificates_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='Stores user certificates information';
